universe = parallel

executable = openmpiscript.sh

arguments = ./KMEANS_omp_mpi.out /home/deblasio_2082600/Parallel-KMeans/test_files/input100D2.inp 15 5000 1 0.0001 out100D2ompmpi.txt 1

should_transfer_files = YES

transfer_input_files = ./KMEANS_omp_mpi.out

when_to_transfer_output = on_exit_or_evict

output = logs/out_omp_mpi.$(NODE)
error = logs/err_omp_mpi.$(NODE)
log = logs/log_omp_mpi.

machine_count = 4
request_cpus = 32

getenv = True

queue