universe = parallel

executable = openmpiscript.sh

arguments = ./KMEANS_mpi.out /home/deblasio_2082600/Parallel-KMeans/test_files/input100D2.inp 20 5000 1 0.0001 out100D2mpi.txt
should_transfer_files = YES

transfer_input_files = ./KMEANS_mpi.out

when_to_transfer_output = on_exit_or_evict

output = logs/out_mpi.$(NODE)
error = logs/err_mpi.$(NODE)
log = logs/log_mpi.

machine_count = 4

getenv = True

queue